[package]
name = "sbml"
version = "0.2.1"
authors = ["Jose Luis Ricon <jose@ricon.xyz>"]
edition = "2018"
description = "A parser for SBML"
license = "MIT OR Apache-2.0"
documentation="https://docs.rs/sbml/"
repository="https://github.com/jlricon/sbml"
readme="README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.10.1"
serde = "1.0.106"
serde_derive = "1.0.106"
serde_plain = "0.3.0"
mathml = "0.4.2"
