name: autoreadme

on:
  # Generate README.md if templates/docs were modified in default branches
  push:
    branches:
      - trunk
    paths:
      - "README.tpl"
      - "lib.rs"
      - "**readme.yml"

jobs:
  readme:
    name: Generate README
    runs-on: ubuntu-latest
    steps: 
      - name: A job to autogenerate README.md
        uses: carrascomj/cargo-readme-action@v1
        with:
          user: carrascomj
          email: carracomurielj@gmail.com
          branch: trunk